### PR TITLE
Fix/slow cmu

### LINKED ISSUE #13: Multipart Upload: CompleteMultipartUpload takes multiple hours to complete for very big files
## Expected Behavior

Due to the backgroundAppend() optimization the request should finish very quickly, even when uploading files of multiple GB.

## Current Behavior

When uploading a 25GB file (or even 1GB) we can observe that the final operation takes a very long time. Often minutes or up to multiple hours, depending on the size of the uploaded file. Client-side this can be observed by `mc` seemingly hanging when the process bar is completely full and the transfer rate slowly ticking down.

### Environment

* gateway nas
* single MinIO instance on NAS

This also happens in distributed setups where we can expect that the MinIO instance receiving the CompleteMultipartUpload has to aggregate large amounts of chunks to a final object. In this particular case however we also observed this in a single node setup on NAS. The behavior might be caused by the underlying NAS, but we should at least analyze which file operations are performed and if there is a way we could optimize this.

## Steps to Reproduce (for bugs)

You'll need to setup a NAS for this to work. I tried replicating the behavior with a local path, but was unable to observe this in a single node setup. For an unrelated reason as mentioned above this will happen when using multiple nodes instead of only one.

## Context

When using `mc` uploading chunks seems to be very quick, but the final request takes hours to complete which is hard to understand from the client-side. Hopefully we can make this a bit more transparent.

### PR DESCRIPTION
**Pull request by rluetzner**
## Description

In combination with a GlusterFS backend we realized that the CompleteMultipartUpload request becomes very slow. The larger the uploaded filesize is, the longer the request will take.

## Motivation and Context

We noticed that for larger filesizes some clients would run into a timeout during CompleteMultipartUpload requests. The default timeout seems to be 1h, which is pretty big. Nevertheless uploading 20 or 50GiB files caused CMU requests that took way longer to complete.

Compared to AWS it is non-intuitive that a CMU request should take so long, but we're willing to accept it, because it's a limitation of the current implementation, which has to put all chunks together into one big file.

This fixes #13 and #11 .

## How to test this PR?

Tests can easily be performed manually. `time` is helpful in tracking the total duration on the client side, whereas `mc admin trace -v -a` will log all requests including their duration.
If large files are required `truncate -s 100G file` can help you quickly create a file containing only zeros. Without using compression, this is just as good as creating such a big file with actual content, but waaaaay faster.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Review by aweisser — COMMENTED** [review]
Lgtm. But I would like @tristanessquare to take a second look and approve.
@tristanessquare: It's ok that this doesn't have the potential to be merged to the upstream. So please don't take this as criteria.

**Comment by tristanexsquare** [comment]
windows 1.17.x and ubuntu 1.16 testing stages are currently failing. We should fix this before merging.

**Comment by rluetzner** [comment]
@tristanessquare that's fine by me.

**Comment by rluetzner** [comment]
This became more important and I started to look more into the failing unit tests. I'm immensely frustrated and confused why the tests seem to be succeeding for the upstream repository, but fail on our fork.
I've used https://github.com/nektos/act to run the GitHub workflows locally and limited myself to go-lint.yml. To save some resources I've also limited the execution to ubuntu-latest and Go version 1.17.x. I've used the following script:

```bash
#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

sed -i 's/go-version: \[.*$/go-version: \[1.17.x\]/' .github/workflows/go-lint.yml
sed -i 's/os: \[ubuntu-latest, windows-latest\]/os: \[ubuntu-latest\]/' .github/workflows/go-lint.yml

RC=0
act -W .github/workflows/go-lint.yml pull_request || RC=1
git reset --hard
exit $RC
```

I initially wanted to run a `git bisect`, but I discovered that our tests never worked at all. I've run different official RELEASE tags from upstream, the master from upstream and also commits early on when the go-lint.yml was added. None of them succeeded.

I then fell back to running

```bash
~/bisect.sh | tee <branch>.log
```

and `diff`ing the results. I'll attach the log files here.

[fix-slow-cmu.log](https://github.com/iternity-dotcom/minio/files/8714628/fix-slow-cmu.log)
[iternity-rb.log](https://github.com/iternity-dotcom/minio/files/8714629/iternity-rb.log)
[RELEASE.2021-10-13T00-23-17Z.log](https://github.com/iternity-dotcom/minio/files/8714630/RELEASE.2021-10-13T00-23-17Z.log)

Looking at the diff shows that iternity-rb introduced a few tests that fail in a CI environment (they don't when run separately). The same tests fail between iternity-rb and this pull request, which _kinda_ makes this safe to merge. We should address the failing tests ASAP, but I don't see any reason why this merge should be blocked by failing tests.

I'm saying this mostly because the fix gained importance due to a customer being blocked and it might become necessary to merge this without the unit tests succeeding, @tristanessquare . At least it looks like I didn't break anything else.

I only looked at the diff for failed tests, i.e. `diff iternity-rb.log fix-slow-cmu.log | grep 'FAIL:'`.

**Comment by rluetzner** [comment]
I've removed some additional code to make clear that what was previously used as a fallback operation is now the default.

We have no choice but to merge this even with the failing unit tests.

**Review by aweisser — APPROVED** [review]
lgtm

**Comment by rluetzner** [comment]
The same tests failed as always, so I'd say this is safe to merge.

**Pull request merged**
